LEAVE_TYPES = {
    'CONSECUTIVE_WFH_COUNT': 2,
    'CONSECUTIVE_PTO_COUNT': 5,
    'MAX_LEAVES_COUNT': 7,
    'MATERNITY_COUNT': 180,
    'MATERNITY_PAID_COUNT': 90,
    'MATERNITY_UNPAID_COUNT': 90,
    'PATERNITY_COUNT': 10,
    'BLOCK_LEAVE_GAP':90
  }