# Generated by Django 5.0.4 on 2024-05-28 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('is_half_day', models.BooleanField()),
                ('half_day_type', models.CharField(blank=True, choices=[('FH', 'First Half'), ('SH', 'Second Half')], max_length=2, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(max_length=100)),
                ('max_days_allowed', models.IntegerField()),
                ('duration', models.CharField(default=None, max_length=100)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveTrackingApp.ruleset')),
            ],
        ),
        migrations.CreateModel(
            name='StatusReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('A', 'APPROVED'), ('R', 'REJECTED'), ('W', 'WITHDRAWN')], default='P', max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('leave_reason', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('A', 'APPROVED'), ('R', 'REJECTED'), ('W', 'WITHDRAWN')], default='P', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assets_documents', models.FileField(upload_to='')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
                ('day_details', models.ManyToManyField(to='LeaveTrackingApp.daydetails')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveTrackingApp.leavetype')),
                ('status_reasons', models.ManyToManyField(to='LeaveTrackingApp.statusreason')),
            ],
        ),
    ]
