# Generated by Django 5.0.4 on 2024-05-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='duration',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
