# Generated by Django 5.0.4 on 2024-06-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Published', 'Published')], default='Draft', max_length=100),
        ),
    ]
