# Generated by Django 5.0.4 on 2024-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='editReason',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
