# Generated by Django 5.0.4 on 2024-06-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0002_add_initial_data'),
        ('UserApp', '0005_user_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approver_of_leave', to='UserApp.user'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeaveTrackingApp.leavetype'),
        ),
    ]
