# Generated by Django 5.0.4 on 2024-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0003_yearcalendar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='type',
            field=models.CharField(choices=[('Optional', 'Optional'), ('Confirmed', 'Confirmed')], default='Confirmed', max_length=100),
        ),
    ]
