# Generated by Django 5.0.4 on 2024-06-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0003_leave_editreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='editStatus',
            field=models.CharField(choices=[('edited', 'Edited'), ('requested_for_edit', 'Requested For Edit')], max_length=100, null=True),
        ),
    ]
