# Generated by Django 5.0.4 on 2024-06-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0003_alter_leave_approver_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status_reasons',
            field=models.ManyToManyField(blank=True, null=True, to='LeaveTrackingApp.statusreason'),
        ),
    ]
