# Generated by Django 5.0.4 on 2024-06-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0004_alter_leave_status_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='status_reasons',
        ),
    ]
