# Generated by Django 5.0.4 on 2024-07-09 10:49

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0004_alter_leave_editstatus'),
        ('UserApp', '0005_alter_user_work_type'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='comments',
            field=models.ManyToManyField(blank=True, to='common.comment'),
        ),
        migrations.AlterField(
            model_name='statusreason',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statusreason',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_reasons', to='UserApp.user'),
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(max_length=25)),
                ('details', models.JSONField(default=dict, null=True)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policy_type', to='LeaveTrackingApp.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='YearPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('sent_for_approval', 'Sent For Approval')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.ManyToManyField(blank=True, to='common.comment')),
                ('leave_policies', models.ManyToManyField(to='LeaveTrackingApp.leavepolicy')),
            ],
        ),
    ]
