# Generated by Django 5.0.4 on 2024-07-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0005_yearcalendar_comments_leavepolicy_yearpolicy'),
        ('UserApp', '0005_alter_user_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreason',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statusreason',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_reasons', to='UserApp.user'),
        ),
    ]
