# Generated by Django 5.0.4 on 2024-06-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0005_remove_leave_status_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status_reasons',
            field=models.ManyToManyField(blank=True, to='LeaveTrackingApp.statusreason'),
        ),
    ]
