# Generated by Django 5.0.4 on 2024-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0006_yearcalendar_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearcalendar',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('sent_for_approval', 'Sent For Approval')], default='draft', max_length=20),
        ),
    ]
