# Generated by Django 5.0.4 on 2024-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0006_alter_yearcalendar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='info_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
