# Generated by Django 5.0.4 on 2024-07-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0006_add_optional_leave_type'),
        ('common', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='comments',
            field=models.ManyToManyField(blank=True, to='common.comment'),
        ),
        migrations.AddField(
            model_name='yearpolicy',
            name='comments',
            field=models.ManyToManyField(blank=True, to='common.comment'),
        ),
    ]
