# Generated by Django 5.0.4 on 2024-07-26 11:29

from django.db import migrations

def add_data(apps, schema_editor):
    RuleSet = apps.get_model('LeaveTrackingApp', 'RuleSet')
    RuleSet.objects.create(name='optional_leave', max_days_allowed=2, duration='None')

    LeaveType = apps.get_model('LeaveTrackingApp', 'LeaveType')
    optional = RuleSet.objects.get(name='optional_leave')
    
    LeaveType.objects.create(name='optional_leave', rule_set=optional)

class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0007_yearcalendar_info_text'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
