# Generated by Django 5.0.4 on 2024-08-01 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0008_add_optional_leave'),
        ('UserApp', '0006_user_is_current_address_same'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_calendar_created_by', to='UserApp.user'),
        ),
        migrations.AddField(
            model_name='yearpolicy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_policy_created_by', to='UserApp.user'),
        ),
    ]
