# Generated by Django 5.0.4 on 2024-08-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0008_add_optional_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='assets_documents',
            field=models.FileField(blank=True, null=True, upload_to='media/leave_docs/'),
        ),
    ]
