# Generated by Django 5.0.4 on 2024-08-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0010_yearcalendar_created_by_yearpolicy_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydetails',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
