# Generated by Django 5.0.4 on 2024-08-26 10:56

from django.db import migrations

def add_initial_data(apps, schema_editor):
    RuleSet = apps.get_model('LeaveTrackingApp', 'RuleSet')
    RuleSet.objects.create(name='block_leave_pto', max_days_allowed=5, duration='None')
    RuleSet.objects.create(name='block_leave_wfh', max_days_allowed=2, duration='None')
    
class Migration(migrations.Migration):

    dependencies = [
        ('LeaveTrackingApp', '0011_daydetails_is_withdrawn'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]




