# Generated by Django 5.0.4 on 2024-06-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PushNotificationApp', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='redireactionUrl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='types',
            field=models.CharField(choices=[('Leave-Request', 'Leave Request'), ('Upcoming-Holidays', 'Upcoming Holidays')], max_length=100, verbose_name='notification types'),
        ),
    ]
