# Generated by Django 5.0.4 on 2024-10-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PushNotificationApp', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('leave_request', 'Leave Request'), ('leave_requested_by_creator', 'Leave Requested by Creater'), ('leave_request_for_approver', 'Leave Request for Approver'), ('calendar', 'Calendar'), ('leave_policy', 'Leave Policy')], default='leave_request', max_length=100, verbose_name='notification type'),
        ),
    ]
