# Generated by Django 5.0.4 on 2024-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(default='ANghYDiIdo1', max_length=12, primary_key=True, serialize=False),
        ),
    ]
