# Generated by Django 5.0.4 on 2024-06-10 06:49

from django.db import migrations

def add_initial_data(apps, schema_editor):
    Department = apps.get_model('UserApp', 'Department')
    Department.objects.create(department_key='ui_ux', department_name='UI/UX Designing')
    Department.objects.create(department_key='vd', department_name='Visual Designing')
    Department.objects.create(department_key='development', department_name='Development')
    Department.objects.create(department_key='qa', department_name='QA')
    Department.objects.create(department_key='hr', department_name='HR')
    Department.objects.create(department_key='marketing', department_name='Marketing')
    Department.objects.create(department_key='sales', department_name='Sales')

    Role = apps.get_model('UserApp', 'Role')
    Role.objects.create(role_key='admin', role_name='Admin')
    Role.objects.create(role_key='member', role_name='Team Member')
    Role.objects.create(role_key='hr', role_name='HR')
    Role.objects.create(role_key='lead', role_name='Team Lead')

class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]

