# Generated by Django 5.0.4 on 2024-05-29 12:14

from django.db import migrations

def add_initial_data(apps, schema_editor):
    Department = apps.get_model('UserApp', 'Department')
    Department.objects.create(department_key='ui_ux', department_name='UI/UX Designer')
    Department.objects.create(department_key='vd', department_name='Visual Designer')
    Department.objects.create(department_key='developer', department_name='Developer')
    Department.objects.create(department_key='qa', department_name='QA')
    Department.objects.create(department_key='hr', department_name='HR')
    Department.objects.create(department_key='marketing', department_name='Marketing')
    Department.objects.create(department_key='sales', department_name='Sales')

    Role = apps.get_model('UserApp', 'Role')
    Role.objects.create(role_key='admin', role_name='Admin')
    Role.objects.create(role_key='employee', role_name='Employee')
    Role.objects.create(role_key='hr', role_name='HR')
    Role.objects.create(role_key='lead', role_name='Lead')

class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
