# Generated by Django 5.0.4 on 2024-06-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
