# Generated by Django 5.0.4 on 2024-06-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_add_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='user',
            name='app_registration_status',
            field=models.BooleanField(default=False),
        ),
    ]
