# Generated by Django 5.0.4 on 2024-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_type',
            field=models.CharField(choices=[('In-Office', 'In-Office'), ('Work-From-Home', 'Work-From-Home')], max_length=15, null=True),
        ),
    ]
