# Generated by Django 5.0.6 on 2024-06-11 12:36

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_user_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergency_contact_number',
            field=models.BigIntegerField(null=True, validators=[UserApp.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(max_length=250),
        ),
    ]
