# Generated by Django 5.0.4 on 2024-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_isdeleted_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_status',
            field=models.JSONField(null=True),
        ),
    ]
