# Generated by Django 5.0.4 on 2024-05-28 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=uuid.UUID('2e3d115a-8e5c-40b0-88a2-d1038f0bb7ec'), on_delete=django.db.models.deletion.PROTECT, to='UserApp.department'),
        ),
    ]
