# Generated by Django 5.0.4 on 2024-06-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_user_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(max_length=250),
        ),
    ]
