# Generated by Django 5.0.4 on 2024-06-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
