# Generated by Django 5.0.4 on 2024-07-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_user_onboarding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_type',
            field=models.CharField(choices=[('in_office', 'In-Office'), ('work_from_home', 'Work-From-Home')], max_length=15, null=True),
        ),
    ]
