# Generated by Django 5.0.4 on 2024-05-28 09:47

from django.db import migrations

def add_initial_data(apps, schema_editor):
    Role = apps.get_model('UserApp', 'Role')
    Role.objects.create(role_key='hr', role_name='HR')
    Role.objects.create(role_key='lead', role_name='Lead')


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_user_department'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
