# Generated by Django 5.0.4 on 2024-07-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_user_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_curr_address_same',
            field=models.BooleanField(default=True),
        ),
    ]
