# Generated by Django 5.0.4 on 2024-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_user_is_current_address_same'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_address_line',
            new_name='current_address_line1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='permanent_address_line',
            new_name='permanent_address_line1',
        ),
        migrations.AddField(
            model_name='user',
            name='current_address_line2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address_line2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
